# Audio configuration
audio_length: 0.06     # 0.08 for batvision model # 0.064 for modified model
audio_normalize: True
audio_path: dataset/echoes_navigable
audio_sampling_rate: 44100
chirp_params:
    f_start: 20
    f_end: 20000
    T_chirp: 0.003
    fs: 44100
    fc: 10500
    c: 343
audio_type: 3ms_sweep
raw_audio: False
# audio_shape: [2, 257, 166]
audio_shape: [2, 256, 166]
target_audio_shape: [2, 256, 256]

# Model configuration
unet_ngf: 64
unet_input_nc: 3
unet_output_nc: 1


# Training configuration
mode: train
load_pretrained: false
pretrained_ep_num: 300
batchSize: 32
checkpoints_dir: checkpoints/
dataset: replica
enable_cropping: true
enable_img_augmentation: false
expr_dir: checkpoints/
gpu_ids: [0]
nThreads: 0
lr_audio: 0.0001
optimizer: adam
beta1: 0.9 # momentum for sgd, beta1 for adam
weight_decay: 0.0005
epoch_save_freq: 20
decay_factor: 0.94
learning_rate_decrease_itr: -1
niter: 400
display_freq: 20

# validation configuration
validation_freq: 82
validation_on: True


# Testing configuration
mode: test
test_checkpoints_dir: checkpoints/
checkpoint_ep_num: 60

# Dataset configuration
image_resolution: 128
image_transform: true
img_path: dataset/scene_observations_128.pkl
isTrain: True
max_depth: 10.29    # 10.976 for cut the direct path, 10.29 for no cut
min_depth: 0        # 0.686 for cut the direct path ,0 for no cut
metadatapath: dataset/metadata
scenes:
    train: 
        - apartment_0
        - apartment_1
        - frl_apartment_0
        - frl_apartment_1
        - frl_apartment_2
        - frl_apartment_3
        - office_0
        - office_1
        - office_2
        - hotel_0
        - room_0
        - room_1
        - room_2
        - frl_apartment_4
    test: 
        - apartment_2
        - frl_apartment_5
        - office_4
    val: 
        - office_4


# baseline options: 
# batvision, audiodepth, fcrn_mix_multi_pointnet,
# fcrn_angular_q_mix_multi_pointnet, fcrn_decoder
model_baseline: fcrn_angular_q_mix_multi_pointnet   
depth_norm: True
preprocess: resize